## Лабораторная работа №1 | Вариант 2

Выполнил: Филиппов Владимир Михайлович

### 1. Numpy

In [1]:
import numpy as np

1. Создайте матрицу размером 8х8 и заполните ее шахматным рисунком

In [16]:
def chess_order(i, j):
    return (i + j) % 2 == 0

np.fromfunction(chess_order, (8, 8), dtype=int)


array([[ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True],
       [ True, False,  True, False,  True, False,  True, False],
       [False,  True, False,  True, False,  True, False,  True]])

2. Каков результат выполнения следующих выражений?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [25]:
np.array(0) / np.array(0) # ну типа вернет np.nan вместо исключения (и кинуло ворнинг)
np.array(0) // np.array(0) # вернет 0 и кинуло ворнинг
np.array([np.nan]).astype(int).astype(float) #ворнинг о неправильном касте + массив заполненный какой-то шляпой

/tmp/ipykernel_15292/1746395532.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0) # ну типа вернет np.nan вместо исключения (и кинуло ворнинг)
/tmp/ipykernel_15292/1746395532.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) # вернет 0 и кинуло ворнинг
/tmp/ipykernel_15292/1746395532.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float) #ворнинг о неправильном касте + массив заполненный какой-то шляпой


array([-9.22337204e+18])

3. Создайте матрицу-шахматную доску 8х8 используя функцию `tile`

In [28]:
np.tile([[1,0], [0,1]], (4,4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

4. Как округлить до целых массив чисел с плавающей точкой?

In [31]:
a = np.array([1.1, 2.1, 3.7])
np.round(a).astype(int)

array([1, 2, 4])

5. Как найти общие значения между двумя массивами?

In [32]:
a = np.array([1,2,3])
b = np.array([3,4,5])
np.intersect1d(a,b)

array([3])

6. Как вычислить ((A+B)*(-A/2)) на месте (без копирования)?

In [36]:
(a + b) * (-a / 2)


array([ -2.,  -6., -12.])

7. Рассмотрим случайный вектор с формой 100х2, представляющей координаты, и найдем расстояния от точки к точке

In [52]:
a = np.random.randint(0,100,(100,2))
np.linalg.norm(a[1:]- a[:-1], axis=1)

array([ 25.        ,  30.06659276,  11.18033989,  47.04253395,
        86.05230967,  78.85429601,  44.82186966,  75.2861209 ,
        86.3539229 ,  34.13209633,  56.32051136,  86.31338251,
        62.20128616,  32.20248438,  27.65863337,  72.71863585,
        44.59820624,  59.43904441,  62.64183905,   8.06225775,
        56.30275304,  92.19544457,  23.19482701,  52.20153254,
        59.03388857,  24.75883681,  24.69817807,  88.10221337,
        65.27633568,  75.2861209 ,  82.07313811,  40.01249805,
        51.26402247,  46.17358552,  33.30165161,  82.60750571,
        64.32728814,  62.58594091,  34.4818793 ,  78.49203781,
        89.47066558,  39.81205847,  60.44005295,  79.        ,
        33.30165161,  22.56102835,  64.81512169,  62.48199741,
        27.89265136,  66.49060084,  59.22837158,  92.09777413,
        26.47640459,  18.02775638,   5.38516481,  60.44005295,
        19.6468827 ,  62.64183905,  98.97979592,  79.93122043,
        57.07013229,  66.73080248,  54.58937626,  43.27

8. Как конвертировать массив float(32 bit) к массиву целых чисел (integer 32 bit) in place?

In [68]:
a = np.array([1.,2.,3.])
a.astype(np.int32, copy=False) # не уверен, что имеется ввиду, но надеюсь, что это и имеется

array([1, 2, 3], dtype=int32)

9. Создайте структурированный массив, представляющий позицию (x, y) и цвет (r, g, b).

In [94]:
color = np.random.randint(0, 256, size=(10, 3))
pos = np.random.randint(-100, 100, size=(10, 2))
np.column_stack((color, pos))

array([[193, 123, 203, -38, -45],
       [ 66, 169, 119,  97,  92],
       [ 91, 242, 167,  41, -51],
       [126, 163, 107,  53,  14],
       [  4, 102,  19, -74, -71],
       [ 54, 155,  85, -24,  57],
       [ 60,   8,  32, -97, -78],
       [ 96,  89,   5,  35, -25],
       [208, 155, 132,  64,   7],
       [155, 135,  61, -34,  38]])

10. Какой эквивалент enumerate для numpy массивов?

In [97]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for idx, value in np.ndenumerate(arr):
    print(idx, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


### 2. Pandas

Найдите ответы на вопросы или выполните действия с предложенным датасетом 

Данные о преступлениях, совершенных женщинами в Индии, с демографическими подробностями.

Файл: `CrimesOnWomenData.csv`

```
State - название штата/региона
Year - год записи
Rape - случаи изнасилования
K&A - случаи похищения 
DD - смерти из-за приданого
AoW - нападение на женщин
AoM - нападение на женскую скромность(modestity)
DV - бытовое насилие
WT - торговля женщинами
```

In [2]:
import pandas as pd

In [3]:
DATA_PATH = "data/CrimesOnWomenData.csv"
df = pd.read_csv(DATA_PATH)
df.head()

Unnamed: 0              State  Year  Rape   K&A   DD   AoW   AoM    DV  WT
0           0     ANDHRA PRADESH  2001   871   765  420  3544  2271  5791   7
1           1  ARUNACHAL PRADESH  2001    33    55    0    78     3    11   0
2           2              ASSAM  2001   817  1070   59   850     4  1248   0
3           3              BIHAR  2001   888   518  859   562    21  1558  83
4           4       CHHATTISGARH  2001   959   171   70  1763   161   840   0

1. За какие года представлен набор данных?

In [4]:
df["Year"].unique()

array([2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
       2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021])

2. Выявите район с самым высоким количеством убийств женщин

In [14]:
df[df["DD"] == df['DD'].max()]["State"]

582    Uttar Pradesh
Name: State, dtype: object

3. Какое среднее число изнасилований женщин в индии наблюдалось в указанные года?

In [28]:
pd.DataFrame(df.groupby("Year")["Rape"].mean()) # avg_rapes = df['Rape'].mean()

Rape
Year             
2001   461.588235
2002   469.705882
2003   451.676471
2004   520.058824
2005   520.617647
2006   550.735294
2007   592.323529
2008   617.676471
2009   615.529412
2010   637.205882
2011   672.388889
2012   692.305556
2013   936.305556
2014  1020.416667
2015   962.527778
2016  1081.861111
2017   904.416667
2018   926.555556
2019   889.805556
2020   779.055556
2021   879.916667

4. Выявите район с минимальным числом похищений за период 2001-2003 года

In [19]:
df[(df["K&A"] == df['K&A'].min()) & (df["Year"] <= 2003) & (df["Year"] >= 2001)]

Unnamed: 0        State  Year  Rape  K&A  DD  AoW  AoM  DV  WT
32           32  LAKSHADWEEP  2001     0    0   0    0    0   0   0
66           66  LAKSHADWEEP  2002     1    0   0    1    0   0   0
90           90       SIKKIM  2003    10    0   0   25    0   1   0
100         100  LAKSHADWEEP  2003     2    0   0    1    0   1   0

5. Перечислите районы в которых наблюдались наиболее частые случае домашнего насилия за период с 2005 по 2012 года

6. Выведите названия районов в порядке не возрастания случаев торговли женщинами за 2020 год

Перейдем к следующему набору данных.

Файл: `CustomerPurchasingBehaviors.csv`

Этот набор данных содержит информацию о профилях клиентов и их покупательском поведении. Данные содержат столбцы, содержащие идентификатор пользователя, возраст, годовой доход, сумму покупки, показатель лояльности (в разбивке по классам), регион и частоту покупок. Он предназначен для анализа тенденций сегментации клиентов и лояльности и может быть использован для различных задач машинного обучения и анализа данных, связанных с поведением клиентов и исследованиями рынка.

```
user_id - ID клиента
age - Возраст
annual_income - Годовой доход клиента (в долларах США).
purchase_amount - Общая сумма покупок, совершенных клиентом (в долларах США).
loyalty_score - Показатель лояльности клиента (значение от 0 до 100).
region - Регион, в котором проживает клиент (Север, Юг, Восток, Запад).
purchase_frequency - Частота покупок клиентов (количество раз в год).
```

In [ ]:
# Load dataset here

8. Какой средний годовой доход у клиентов с уровнем лояльности больше 50 живущих на севере

9. Выведите 25 и 75 перцентили уровня лоальности клиентов живущих на западе с частотой покупок более 20 раз в год

10. Отличается ли медианный возраст клиентов с уровнем лояльности более 70 и менее 10 для жителей Востока и Севера.

### 3. Визуализация

Используя библиотеки matplotlib/sns/plotly/pandas и набор данных представленный ранее визуализируйте

1. Постройте диаграмму которая отражает средний уровень лояльности во всех регионах

2. Постройте гистограмму распределения зарплат клиентов на Севере.

3. Сравните уровни зарплат людей на севере и юге.

4. Постройте box plot отображающий распределение уровня лояльности для людей до 20 лет, от 20 до 40, от 40 до 60 и старше 60 лет

5. Визуализируйте зависимость частоты покупок от заработка

6. Визуализируйте как зависит сумма покупок от зарплаты клиента

7. Придумайте как визуализировать зависимость между частотой покупок, суммой покупок и скором лояльности *

\* Задание на доп. балл